### ISSUE TITLE
New colaborator: 

### ISSUE THREAD

**Issue by ricky00012** [Cartesianism/Registration#3]
**Anonymous contacts**

Niсkname:  ricky00012
Email:  rick.shwaiger@gmail.com

**Specialization**

My areas are making telegram bots like common accounts, inviting to telegram groups, sending messages by telegram accounts, anything related to telegram I can do. Also I can make simulation of conversation by bots in telegram chat. I also have access to an unlimited number of free proxies through tor

**Skills**

Python development(flask), web development(php), working with Maria db, mysql, PostgreSQL

**Time resource**

**Comment by withspear** [comment]
Added
