### ISSUE TITLE
New colaborator: 

### ISSUE THREAD

**Issue by Rvkinh711** [Cartesianism/Registration#5]
Read how to join before registration: https://github.com/Cartesianism/Manifesto

**Anonymous contacts**

Niсkname: Rvkinh711
Email: rvkinh711@gmail.com

**Specialization**

Senior UX Designer

**Skills**

All relevant UI/UX software (Adobe Photoshop, illustrator, after effects, XD; Figma; Blender) and skills. 5 years of experience in this medium. Basic knowledge of HTML, CSS, and JavaScript 

**Time resource**

about 2-4 hours every day

**Comment by withspear** [comment]
Added
