### ISSUE TITLE
New colaborator: 

### ISSUE THREAD

**Issue by eSsPhPcsazUj** [Cartesianism/Registration#7]
Read how to join before registration: https://github.com/Cartesianism/Manifesto

**Anonymous contacts**

Niсkname: eSsPhPcsazUj (required)  
Email: eSsPhPcsazUj@outlook.com (required)  

**Specialization**

Senior Developer

**Skills**

.NET, C#, JavaScript, vue
#1 back end 
#5 front end

**Time resource**
1-4 h/day

**Comment by withspear** [comment]
Added
